# Generated by Django 5.2.12 on 2026-04-04 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('channel', models.CharField(choices=[('sms', 'SMS'), ('dashboard', 'Dashboard')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result')], max_length=15)),
                ('content', models.TextField()),
                ('tool_name', models.CharField(blank=True, max_length=100, null=True)),
                ('tool_input', models.JSONField(blank=True, null=True)),
                ('tool_output', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent.agentsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('area_acres', models.FloatField()),
                ('soil_type', models.CharField(max_length=100)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='agentsession',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='agent.field'),
        ),
        migrations.CreateModel(
            name='ActionRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('irrigate', 'Irrigate'), ('fertilize', 'Fertilize'), ('pest_alert', 'Pest Alert'), ('harvest', 'Harvest'), ('no_action', 'No Action')], max_length=15)),
                ('urgency', models.CharField(choices=[('immediate', 'Immediate'), ('within_24h', 'Within 24 Hours'), ('within_3d', 'Within 3 Days'), ('monitor', 'Monitor')], max_length=15)),
                ('description', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_if_delayed', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='agent.agentsession')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='agent.field')),
            ],
        ),
    ]
