# Generated by Django 5.2.12 on 2026-04-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmessage',
            name='duration_ms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('tool_call', 'Tool Call'), ('tool_result', 'Tool Result'), ('field_agent', 'Field Agent'), ('orchestrator', 'Orchestrator'), ('recommender', 'Recommender'), ('final_response', 'Final Response')], max_length=20),
        ),
    ]
