# Generated by Django 5.2.12 on 2026-04-05 00:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentmessage_duration_ms_alter_agentmessage_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionrecommendation',
            name='cost_breakdown',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='actionrecommendation',
            name='implementation_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='actionrecommendation',
            name='timing_rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='CropHealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ndvi_score', models.FloatField()),
                ('stress_level', models.CharField(max_length=20)),
                ('vegetation_trend', models.CharField(max_length=50)),
                ('vegetation_fraction', models.FloatField()),
                ('last_satellite_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_health_records', to='agent.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoilProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soil_type', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('organic_matter_pct', models.FloatField()),
                ('drainage_class', models.CharField(max_length=50)),
                ('water_holding_capacity', models.CharField(max_length=50)),
                ('available_water_in_per_ft', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_profile', to='agent.field')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_f', models.FloatField()),
                ('temp_c', models.FloatField()),
                ('humidity_pct', models.FloatField()),
                ('wind_mph', models.FloatField()),
                ('conditions', models.CharField(max_length=255)),
                ('uv_index', models.FloatField(blank=True, null=True)),
                ('precipitation_forecast', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='agent.field')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='agent.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
