# Generated by Django 5.2.12 on 2026-04-05 03:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_actionrecommendation_cost_breakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('price_per_unit', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('trend_30d', models.CharField(max_length=50)),
                ('seasonal_outlook', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='agent.field')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='market_snapshots', to='agent.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PestRiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(max_length=20)),
                ('primary_threats', models.JSONField(default=list)),
                ('preventive_actions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pest_assessments', to='agent.field')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pest_assessments', to='agent.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterUsageEstimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daily_need_gal', models.IntegerField()),
                ('deficit_pct', models.IntegerField()),
                ('recommendation', models.TextField()),
                ('est_cost', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_estimates', to='agent.field')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='water_estimates', to='agent.agentsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
