# Generated by Django 5.2.12 on 2026-04-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_marketsnapshot_pestriskassessment_waterusageestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentsession',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('dashboard', 'Dashboard'), ('chat', 'Chat')], max_length=10),
        ),
    ]
