import uuid
from django.db import models


class Field(models.Model):
    """Registered field with location and crop information."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)  # e.g. "North 40"
    crop_type = models.CharField(max_length=50)  # cotton, alfalfa, citrus
    lat = models.FloatField()  # Latitude
    lng = models.FloatField()  # Longitude
    area_acres = models.FloatField()
    soil_type = models.CharField(max_length=100, blank=True)  # From USDA data
    owner_phone = models.CharField(max_length=20)  # E.164 format
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.crop_type})"


class AgentSession(models.Model):
    """Conversation thread with a farmer."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = models.CharField(max_length=20)  # Farmer's phone
    field = models.ForeignKey(Field, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Session {self.id.hex[:8]} - {self.phone_number}"


class AgentMessage(models.Model):
    """Individual message or tool call in a session."""
    ROLE_CHOICES = [
        ('user', 'User'),
        ('field_agent', 'Field Agent'),
        ('orchestrator', 'Orchestrator Agent'),
        ('recommender', 'Recommender Agent'),
        ('tool_call', 'Tool Call'),
        ('tool_result', 'Tool Result'),
        ('final_response', 'Final Response'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(AgentSession, on_delete=models.CASCADE, related_name='messages')
    role = models.CharField(max_length=20, choices=ROLE_CHOICES)
    content = models.TextField()  # Message text or tool output

    # Tool call metadata (nullable for non-tool messages)
    tool_name = models.CharField(max_length=50, blank=True)
    tool_input = models.JSONField(blank=True, null=True)  # Tool parameters
    tool_output = models.JSONField(blank=True, null=True)  # Tool response
    duration_ms = models.IntegerField(blank=True, null=True)  # Execution time

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_at']

    def __str__(self):
        return f"{self.role}: {self.content[:50]}..."


class ActionRecommendation(models.Model):
    """Structured recommendation generated by the agent."""
    ACTION_TYPES = [
        ('irrigate', 'Irrigate'),
        ('fertilize', 'Fertilize'),
        ('pest_alert', 'Pest Alert'),
        ('harvest', 'Harvest'),
        ('no_action', 'No Action'),
    ]

    URGENCY_LEVELS = [
        ('immediate', 'Immediate'),
        ('within_24h', 'Within 24 Hours'),
        ('within_3d', 'Within 3 Days'),
        ('monitor', 'Monitor'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(AgentSession, on_delete=models.CASCADE)
    field = models.ForeignKey(Field, on_delete=models.CASCADE)

    action_type = models.CharField(max_length=20, choices=ACTION_TYPES)
    urgency = models.CharField(max_length=15, choices=URGENCY_LEVELS)
    description = models.TextField()  # Human-readable recommendation
    estimated_cost = models.DecimalField(max_digits=8, decimal_places=2)  # Dollar cost
    risk_if_delayed = models.TextField()  # What happens if farmer waits

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"{self.action_type.title()} - {self.urgency} (${self.estimated_cost})"